# Generated by Django 5.1.1 on 2024-09-09 04:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=3)),
                ('nombre', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(blank=True, max_length=10, null=True)),
                ('celular', models.CharField(max_length=10)),
                ('correo', models.EmailField(max_length=254)),
                ('url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Domicilio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pais', models.CharField(max_length=20)),
                ('estado', models.CharField(max_length=20)),
                ('ciudad', models.CharField(max_length=20)),
                ('colonia', models.CharField(max_length=20)),
                ('cp', models.CharField(max_length=5, verbose_name='Codigo postal')),
                ('calle', models.CharField(max_length=20)),
                ('ne', models.CharField(max_length=10, verbose_name='Numero exterior')),
                ('ni', models.CharField(blank=True, max_length=10, null=True, verbose_name='Numero interior')),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Medida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40, verbose_name='Nombre(s)')),
                ('apellidos', models.CharField(max_length=40)),
                ('genero', models.CharField(choices=[('', 'Seleccione una opcion'), ('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('contacto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='caja.contacto')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Fiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfc', models.CharField(max_length=8)),
                ('rs', models.CharField(max_length=30, verbose_name='Razon social')),
                ('domicilio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='caja.domicilio')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40, verbose_name='Nombre(s)')),
                ('apellidos', models.CharField(max_length=40)),
                ('contacto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='caja.contacto')),
                ('fiscal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='caja.fiscal')),
            ],
        ),
        migrations.CreateModel(
            name='Negocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('contacto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='caja.contacto')),
                ('fiscal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='caja.fiscal')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=10)),
                ('descripcion', models.TextField()),
                ('existencia', models.IntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Precio de venta')),
                ('existencia_minima', models.IntegerField(verbose_name='Existencia minima')),
                ('departamento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='caja.departamento')),
                ('marca', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='caja.marca')),
            ],
        ),
    ]
