# Generated by Django 5.1.1 on 2024-09-10 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='rol',
            field=models.CharField(choices=[('', 'Seleccione un rol'), ('A', 'Administrador'), ('E', 'Empleado')], default='E', max_length=1),
        ),
    ]
