# Generated by Django 5.1.1 on 2024-09-12 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0002_empleado_rol'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimentoCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('monto_abierto', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Monto de apertura')),
                ('monto_cierre', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Monto de cierre')),
                ('saldo_final', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('movimiento', models.CharField(max_length=1)),
                ('caja', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='caja.caja')),
                ('empleado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='caja.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=11)),
                ('total', models.DecimalField(decimal_places=2, max_digits=11)),
                ('cantidad', models.IntegerField()),
                ('caja', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='caja.caja')),
                ('producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='caja.producto')),
                ('vendedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='caja.empleado')),
            ],
        ),
    ]
