# Generated by Django 5.1.1 on 2024-09-12 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0003_movimentocaja_venta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentocaja',
            name='monto_cierre',
            field=models.DecimalField(decimal_places=2, max_digits=11, null=True, verbose_name='Monto de cierre'),
        ),
    ]
