# Generated by Django 5.1.1 on 2024-09-12 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0004_alter_movimentocaja_monto_cierre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentocaja',
            name='monto_cierre',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True, verbose_name='Monto de cierre'),
        ),
        migrations.AlterField(
            model_name='movimentocaja',
            name='movimiento',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
