# Generated by Django 5.1.1 on 2024-09-12 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0005_alter_movimentocaja_monto_cierre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentocaja',
            name='monto_abierto',
            field=models.DecimalField(decimal_places=2, max_digits=11, null=True, verbose_name='Monto de apertura'),
        ),
    ]
