# Generated by Django 5.1.1 on 2024-09-13 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0006_alter_movimentocaja_monto_abierto'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='descuento',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movimentocaja',
            name='monto_abierto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True, verbose_name='Monto de apertura'),
        ),
    ]
