# Generated by Django 5.1.1 on 2024-09-19 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0007_venta_descuento_alter_movimentocaja_monto_abierto'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='caja.cliente'),
        ),
    ]
